name: Test add.py Execution

on:
  pull_request:
    branches:
      - "main"

jobs:
  check-add-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if add.py exists in PR
        id: check_file
        run: |
          git fetch origin main
          if git diff --name-only HEAD^ HEAD | grep -q "add.py"; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Run add.py if exists
        if: env.exists == 'true'
        run: |
          chmod +x add.py
          OUTPUT=$(python3 add.py 9 5)
          echo "result=$OUTPUT" >> $GITHUB_ENV

      - name: Validate output
        if: env.exists == 'true'
        run: |
          if [ "$result" -ne 14 ]; then
            echo "add.py did not return 14, failing the job."
            exit 1
          fi
